#!/usr/bin/perl -w

# Title: TurtleWax
# Desc: The fix for Shell-Shock, just ask the Ninja Turtles
# Author: Chris Hart
# Date: 2014.09.30

use strict;
use Getopt::Long;

my ($f,$h,$help);
my @servers;

GetOptions (
	'f=s'	=> \$f,
	'h=s'	=> \$h,
	'help!'	=> \$help,
);

&usage() if ( $help );

if($f) {
    open(FILE, "<$f");
        @servers = <FILE>;
    close(FILE);
} elsif ( $h ) {
	@servers = ( $h );
}

&usage() unless ( @servers );

print "\033[0;32m~TurtleWax~\033[0m\n";
print "   \033[1;35m* \"Heroes on a half-shell...\"\033[0m\n\n";

foreach my $host ( @servers ) {
	my( $squeeze, $wheezy );
	chomp $host;

	print "	\033[0;36m=== $host ===\033[0m\n";

	my $ver = `ssh $host "cat /etc/debian_version 2>/dev/null" 2>/dev/null`;

	unless ( $ver ) {
		printf( "	\033[0;31m%20s", "* Connection Error\n\n");
		next;
	}

	$squeeze = 1 if ( $ver =~ /^6\.\d/ );
	$wheezy = 1 if ( $ver =~ /^7\.\d/ );

	unless ( $squeeze or $wheezy ) {
		printf( "	%20s", "* Version Unsupported\n\n");
		next;
	}

	if ( $squeeze and $wheezy ) {
		print "	* Version Issue, please fix debian_version\n\n";
		next;
	}

	my $shocked = `ssh $host "env X='() { :;} ; echo -n busted' /bin/bash -c 'echo -n stuff'|grep busted"`;

	if ( $shocked ) {
		print "	\033[0;32m* Oh No, this one has been \033[1;32mShellShocked\033[0;32m!\033[0m\n";
	} else {
		print "	\033[0;32m* No \033[1;32mShellShock\033[0;32m here,  Radical Dude!\033[0m\n";
		print "\n";
		next;
	}

	####

	my ( $result, $source );

	# deb http://http.debian.net/debian/ squeeze-lts main contrib non-free
	if ( $squeeze ) {
		$source = "deb http://http.debian.net/debian/ squeeze-lts main contrib non-free";
	} elsif ( $wheezy ) {
		$source = "deb http://http.debian.net/debian/ wheezy main contrib non-free"
	}
	
	# 1. Append line to Apt/Sources

	$result = `ssh $host "echo '$source' >> /etc/apt/sources.list"`;

	if ( $result ) {
		print "	\033[0;31mWARN: ";
		print $result;
		print "\033[0m\n";
		next;
	}

	# 2. Run apt-get update
	
	$result = `ssh $host "apt-get update"`;

	# 3. Exec security patch
	
	$result = `ssh $host "wget -O - http://security.zerolag.com/updateme.sh | bash"`;

	# 4. Remove sources line
	
	$result = `ssh $host "perl -pi -e 's/.+debian\\\.net.+//g' /etc/apt/sources.list"`;

	if ( $result ) {
		print "	\033[0;31mWARN: ";
		print $result;
	}

	# 5. Run apt-get update... again.
	
	$result = `ssh $host "apt-get update"`;

	# 6. Verify bash
	
	$result = `ssh $host "dpkg -l | grep 'bash ' | awk '{print\\\$3}'"`;

	# squeeze: 4.1-3+deb6u1
	# wheezy: 4.2+dfsg-0.1+deb7u3
	
	my $ok = "	\033[0;31m* Wipeout!\n";
	
	if ( $squeeze ) {
		$ok = "	\033[0;32m* Cowabunga!\n" if ( $result =~ /4\.1-3\+deb6u2/ );
	} elsif ( $wheezy ) {
		$ok = "	\033[0;32m* Cowabunga!\n" if ( $result =~ /4\.2\+dfsg-0\.1\+deb7u3/ );
	}

	printf( "%7s\033[0m", $ok );
	print "\n";

}

sub usage {
	die "Usage: $0 [OPTIONS]
Desc: TurtleWax for ShellShocked turtles.

    [OPTIONS]
	-f	FILE of hosts
	-h	a single HOST

#TurtlePower\n";
}

